services:
  - type: worker
    name: frexy-auto-like-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: API_KEY
        value: JMLB
      - key: API_BASE
        value: https://samiullike-production.up.railway.app
      - key: CHANNELS
        value: "FREXY Updates|https://t.me/FREXY_OFC,FREXY Chat|https://t.me/FREXY_CHATS"
    disk:
      name: bot-data
      mountPath: /opt/render/project/src/bot_data
      sizeGB: 1
